Controllers/FileBrowserController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace EviCRM.Portal.Controllers
{
    public class FileBrowserController : Controller
    {
        IWebHostEnvironment Environment;

        public FileBrowserController(IWebHostEnvironment enviroment)
        {
            Environment = enviroment;
        }


        public FileResult OnGetDownloadFile(string fileName)
        {
            string path = Path.Combine(Environment.WebRootPath, "store", fileName);

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        // GET: FileBrowserController
        public ActionResult Index()
        {
            return View();
        }

        // GET: FileBrowserController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FileBrowserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FileBrowserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FileBrowserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FileBrowserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FileBrowserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FileBrowserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/NotesController.cs
using Microsoft.AspNetCore.Mvc;

namespace EviCRM.Portal.Controllers
{
    public class NotesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

       

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Портал EviCRM</title>
    <link rel="stylesheet" href="https://evicrm.site/portal/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://evicrm.site/portal/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="https://evicrm.site/portal/">EviCRM.Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Редактор документов</a>

                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="FileBrowser" asp-action="Index">Список всех документов</a>
                        </li>*@

                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-controller="Notes" asp-action="Index">Заметки</a>*@
                             <a class="nav-link text-dark" href="https://evicrm.site/portal/Notes/">Общие заметки</a>
                        </li>
                         <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-controller="Notes" asp-action="Index">Заметки</a>*@
                             <a class="nav-link text-dark" href="https://evicrm.site/portal/PersonalNotes/">Свои заметки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://evicrm.site/portal/Store">Файловый менеджер</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" href="https://evicrm.site/portal/" target="_blank">Во весь экран</a>
                        </li>
                        @*
                            <li class="nav-item">
                             <a class="nav-link text-dark" href="https://evicrm.site/portal/reqUpload/">Файл в презентацию</a>
                        </li>
                        *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
            @RenderBody()


    @*<script src="https://evicrm.site/portal/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="https://evicrm.site/portal/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://evicrm.site/portal/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://evicrm.site/portal/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>